### ISSUE TITLE
Method not found: 'PoeHUD.Poe.Elements.Inventory PoeHUD.Poe.RemoteMemoryObjects.IngameUIElements.get_InventoryPanel()

### ISSUE THREAD

**Issue by Kronix420** [k-Sacr/MoveToStash#1]
I fixed my original issue. The ini allows me to edit the max tab count. 
However, I am now getting an actual issue. I am getting an error on the latest version of [Poehud](https://github.com/TehCheat/PoEHUD/tree/c8d1ab08feb1bdeda6739baa6d9891519cdcc850)(04/07/2017)

http://image.prntscr.com/image/c91a90ad4f464dfa87071c6659124e15.png
![c91a90ad4f464dfa87071c6659124e15](https://cloud.githubusercontent.com/assets/647790/24822980/cb354548-1bc7-11e7-9ddc-dfa90676bf73.png)

This happens with all plugins that have to do with the inventory (item analyzer, inventory preview, and move to stash). It works perfectly fine on the version I have from Apr.06.2017 however.
The log files of each plugin contains the following repeated for as long as the plugin is running. The only difference is the name of the plugin on line 5: 
```
Log Entry : 7:00:58 PM Friday, April 7, 2017
 Method error: Render : System.MissingMethodException: Method not found: 'PoeHUD.Poe.Elements.Inventory PoeHUD.Poe.RemoteMemoryObjects.IngameUIElements.get_InventoryPanel()'.
   at MoveToStash.MoveToStash.Render()
   at PoeHUD.Plugins.BasePlugin.iRender()
```

Is this issue with the plugins, or with poehud itself? I've posted it in the [poehud git](https://github.com/TehCheat/PoEHUD/issues/125) as well.

**Comment by k-Sacr** [comment]
fixed
